---
language: python
python: "2.7"
services:
  - docker

env:
  matrix:
    - ANSIBLE_VERSION="2.0.0.2"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

# before_install:
#   # Install some dependencies
#   - sudo apt-get update -qq -y
#   - sudo apt-get install -qq -y python-apt python-pycurl locales
#   - echo 'en_US.UTF-8 UTF-8' | sudo tee /var/lib/locales/supported.d/local


install:
  - pip install ansible=="$ANSIBLE_VERSION"

script:
  - echo localhost > inventory

  # Syntax check
  - ansible-playbook -i inventory tests/playbook.yml --syntax-check

  # Play test (also create postgresql_data_directory)
  - ansible-playbook -i inventory tests/playbook.yml --connection=local

  # Testing with docker (experimental)
  - docker build -f tests/Dockerfile-ubuntu16.04 -t pgadmin4_ubuntu16.04
  - docker run 
  # - docker run pgadmin4_ubuntu16.04


# script:
#   # Basic role syntax check
#   - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
#
# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/